name: Create publiccode.yaml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Uses the default testing workflow from https://github.com/CommonGateway/workflows 
jobs:

  create-publiccode:
    name: Create publiccode.yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.2
        with:
          # path: 'src'
          file: 'publiccode.yaml'
          content: |
            publiccodeYmlVersion: "0.1"

            name: "Pet Store"
            url: "https://github.com/CommonGateway/PetStore"
            releaseDate: "2022-06-04"

            softwareType: configurationFiles

            inputTypes:
              - application/json
              - application/xml

            outputTypes:
              - application/json

            platforms:
              - web
              
            categories:
              - collaboration
              - it-development
              
            developmentStatus: beta

            description:
              nl:
                shortDescription: "Een API voor data rondom een dierenwinkel."
                documentation: 'https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/CommonGateway/PetStore/main/OAS.yaml&nocors'
                apiDocumentation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml'
                # testDataLocation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/data/data.json'
              en:
                shortDescription: "An API for data about a pet store."
                documentation: 'https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml&nocors'
                apiDocumentation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/OAS.yaml'
                # testDataLocation: 'https://raw.githubusercontent.com/${{ github.repository }}/main/data/data.json'

            dependsOn:
              open:
                - name: common-gateway
                  versionMin: 1.0.0
