# This is an workflow to autmaticly tests the validity of your OAS definitons and the Common Gateway's abillity to provide an API for them

name: Automated Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pull common-gateway images
        run: docker-compose pull

      - name: Run the docker image
        run: docker-compose up -d

      - name: Create collection and configure gateway with oas
        run: "docker-compose exec -T php bin/console app:load-publiccodes"

      # Install Node.js environment
      - name: set up node
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'

      # Install newman
      - name: Install newman
        run: | 
         npm install -g newman
         npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults    
      
      # Run POSTMAN collection and output the file as html
      - name: Run POSTMAN collection
        run: |
         newman run ./tests/pokemon-api-collection.json -e ./tests/pokemonapi-env.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html

         
      # Upload test results
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: testResults